import React, { forwardRef } from 'react';
import { CartItem } from '../types';

interface ReceiptProps {
  cart: CartItem[];
  date: string;
}

export const ReceiptGenerator = forwardRef<HTMLDivElement, ReceiptProps>(({ cart, date }, ref) => {
  // Group by category for a nicer layout
  const groupedCart: Record<string, CartItem[]> = {};
  cart.forEach(item => {
    if (!groupedCart[item.category]) groupedCart[item.category] = [];
    groupedCart[item.category].push(item);
  });

  return (
    <div 
      ref={ref} 
      className="bg-[#fffcf5] p-8 w-[400px] text-gray-800 font-sans border-2 border-dashed border-gray-300 mx-auto"
      style={{ 
        backgroundImage: 'radial-gradient(#e5e7eb 1px, transparent 1px)', 
        backgroundSize: '20px 20px' 
      }}
    >
      {/* Header */}
      <div className="text-center border-b-2 border-gray-800 pb-4 mb-4">
        <h1 className="text-3xl font-extrabold mb-2 tracking-wider">旺旺苏小餐馆</h1>
        <div className="text-sm text-gray-500 uppercase tracking-widest">Master Menu</div>
        <div className="mt-2 text-xs bg-black text-white px-2 py-1 inline-block rounded">
          {date}
        </div>
      </div>

      {/* Content */}
      <div className="space-y-4">
        {Object.entries(groupedCart).map(([cat, items]) => (
          <div key={cat}>
            <h3 className="text-orange-600 font-bold border-b border-orange-200 text-sm mb-2">{cat}</h3>
            <ul className="space-y-1">
              {items.map((item, idx) => (
                <li key={idx} className="flex justify-between items-center text-sm">
                  <span className="font-bold">{item.name}</span>
                  <span className="text-xs text-gray-400 italic">by {item.addedBy}</span>
                </li>
              ))}
            </ul>
          </div>
        ))}
        
        {cart.length === 0 && (
            <div className="text-center italic text-gray-400 py-4">师傅，还没点菜呢！</div>
        )}
      </div>

      {/* Footer */}
      <div className="mt-8 pt-4 border-t-2 border-gray-800 flex justify-between items-end">
        <div>
          <p className="font-bold text-xl">Total: {cart.length}</p>
          <p className="text-xs text-gray-500">Items</p>
        </div>
        <div className="text-right">
           <div className="w-16 h-16 border-2 border-red-600 rounded-full flex items-center justify-center opacity-80 transform -rotate-12">
             <span className="text-red-600 font-bold text-xs uppercase text-center leading-none">
               Chef<br/>Approve
             </span>
           </div>
        </div>
      </div>
      
      <div className="text-center mt-6 text-xs text-gray-300">
        Generated by 旺旺苏小餐馆 App
      </div>
    </div>
  );
});

ReceiptGenerator.displayName = 'ReceiptGenerator';
