import React, { forwardRef } from 'react';
import { CartItem } from '../types';

interface ReceiptProps {
  cart: CartItem[];
  date: string;
}

export const ReceiptGenerator = forwardRef<HTMLDivElement, ReceiptProps>(({ cart, date }, ref) => {
  // Group by category for a nicer layout
  const groupedCart: Record<string, CartItem[]> = {};
  cart.forEach(item => {
    if (!groupedCart[item.category]) groupedCart[item.category] = [];
    groupedCart[item.category].push(item);
  });

  return (
    <div 
      ref={ref} 
      className="bg-[#fffcf5] p-8 w-[400px] text-gray-800 font-sans border-2 border-dashed border-gray-300 mx-auto relative"
      style={{ 
        backgroundImage: 'radial-gradient(#e5e7eb 1px, transparent 1px)', 
        backgroundSize: '20px 20px' 
      }}
    >
      {/* Tape effect */}
      <div className="absolute -top-3 left-1/2 transform -translate-x-1/2 w-32 h-6 bg-yellow-100/50 rotate-1 border-l border-r border-white/50 backdrop-blur-sm"></div>

      {/* Header */}
      <div className="text-center border-b-2 border-gray-800 pb-4 mb-4">
        <h1 className="text-3xl font-extrabold mb-2 tracking-wider text-gray-900">旺旺苏小餐馆</h1>
        <div className="text-sm text-gray-500 uppercase tracking-widest font-bold">Today's Menu</div>
        <div className="mt-2 text-xs bg-black text-white px-3 py-1 inline-block rounded-full font-mono">
          {date}
        </div>
      </div>

      {/* Content */}
      <div className="space-y-5 min-h-[200px]">
        {Object.entries(groupedCart).map(([cat, items]) => (
          <div key={cat}>
            <h3 className="text-orange-600 font-bold border-b border-orange-200 text-sm mb-2 inline-block pr-4">{cat}</h3>
            <ul className="space-y-2">
              {items.map((item, idx) => (
                <li key={idx} className="flex justify-between items-start text-sm group">
                  <span className="font-bold text-gray-800 relative pl-3">
                    <span className="absolute left-0 top-1.5 w-1.5 h-1.5 bg-gray-300 rounded-full"></span>
                    {item.name}
                  </span>
                  <span className="text-xs text-gray-500 italic bg-gray-100 px-2 py-0.5 rounded-md whitespace-nowrap ml-2">
                    {item.addedBy}
                  </span>
                </li>
              ))}
            </ul>
          </div>
        ))}
        
        {cart.length === 0 && (
            <div className="text-center italic text-gray-400 py-10">师傅，还没点菜呢！<br/>快去加点好吃的~</div>
        )}
      </div>

      {/* Footer */}
      <div className="mt-8 pt-6 border-t-2 border-gray-800 flex justify-between items-end">
        <div>
          <p className="font-bold text-2xl font-mono">{cart.length}</p>
          <p className="text-[10px] uppercase text-gray-500 font-bold tracking-wider">Total Dishes</p>
        </div>
        <div className="text-right">
           <div className="w-20 h-20 border-4 border-red-600 rounded-full flex items-center justify-center opacity-80 transform -rotate-12 hover:rotate-0 transition-transform">
             <div className="w-16 h-16 border border-red-600 rounded-full flex flex-col items-center justify-center">
               <span className="text-red-600 font-black text-xs uppercase text-center leading-none">
                 CHEF<br/>SU<br/>APPROVE
               </span>
             </div>
           </div>
        </div>
      </div>
      
      <div className="text-center mt-8 text-[10px] text-gray-400 font-mono">
        Generated by 旺旺苏小餐馆 App • {new Date().toLocaleTimeString()}
      </div>
    </div>
  );
});

ReceiptGenerator.displayName = 'ReceiptGenerator';